server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 121314
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  redis:
    host: 192.168.192.39
    password: erayt123
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 100


logging:
  config: classpath:logback-spring.xml
  path: e:/boot/start/





